spring:
  cache:
    type: simple
  application:
    name: kotlin-docs-ai-assistant-backend

server:
  port: 8080

ai-platform-token: ${AI_PLATFORM_TOKEN:}

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
  endpoint:
    health:
      show-components: when_authorized
      show-details: when_authorized